import {StyleSheet} from 'react-native';
import theme from '../../../resources/Colors/theme';

const styles = StyleSheet.create({
  headerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: theme.WIDTH_100,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    zIndex: 9999,
    backgroundColor: 'transparent',
  },
  backIndicator: {
    height: 33,
    width: 33,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: theme.BORDER_IMAGE,
    backgroundColor: theme.WHITE_COLOR,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowRadius: 8,
    shadowOpacity: 0.8,
    elevation: 3,
  },
  searchIndicator: {
    marginRight: 6,
    height: 33,
    width: 33,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: theme.BORDER_IMAGE,
    backgroundColor: theme.WHITE_COLOR,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowRadius: 8,
    shadowOpacity: 0.8,
    elevation: 3,
  },
  eventsIndicator: {
    flexDirection: 'row',
    marginLeft: 'auto',
    marginRight: 14,
    height: 33,
    width: 33,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: theme.BORDER_IMAGE,
    backgroundColor: theme.WHITE_COLOR,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowRadius: 8,
    shadowOpacity: 0.8,
    elevation: 3,
  },
  eventsCountContainer: {
    height: 18,
    width: 18,
    position: 'absolute',
    borderRadius: 20,
    backgroundColor: theme.PRIMARY_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
    right: -8.25,
    top: -5,
  },
  eventsCount: {
    fontSize: 11,
    color: theme.WHITE_COLOR,
  },
  marginLeft: {
    marginLeft: 'auto',
    marginRight: 6,
  },
  marginRight: {
    marginRight: 'auto',
    marginLeft: 6,
  },
});

export default styles;
