import {StyleSheet} from 'react-native';
import theme from '../../../resources/Colors/theme';

const styles = StyleSheet.create({
  mainContainer2: {
    width: '46%',
    borderRadius: 8,
    elevation: 2,
    backgroundColor: theme.WHITE_COLOR,
    marginVertical: 7.5,
  },
  pastryImageContainer2: {
    position: 'relative',
  },
  pastryImage2: {
    borderRadius: 8,
    height: 140,
    width: '100%',
    zIndex: 0,
  },
  bestContainer2: {
    position: 'absolute',
    top: 0,
    height: 140,
    borderRadius: 8,
    width: '100%',
  },
  bestInfo2: {
    position: 'absolute',
    top: 9,
    width: '100%',
    paddingHorizontal: 8,
    marginBottom: 'auto',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 99,
  },
  bestInfoButton2: {
    textAlign: 'right',
    marginLeft: 'auto',
  },
  bestDiscount2: {
    backgroundColor: theme.WHITE_COLOR,
    borderRadius: theme.BORDER_IMAGE - 1.5,
    padding: 1.5,
    paddingHorizontal: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bestDiscountText2: {
    fontSize: theme.FONT_SIZE_EXTRA_SMALL - 1.5,
    color: theme.SUCCESS_COLOR,
    marginLeft: 6,
  },
  infoContainer2: {
    position: 'absolute',
    bottom: 9,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
    paddingHorizontal: 8,
    zIndex: 99,
  },
  pastryLikes2: {
    fontSize: theme.FONT_SIZE_EXTRA_SMALL,
    marginLeft: 8,
    color: theme.WHITE_COLOR,
  },
  likesContainer2: {
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
  },
  pastryDetails2: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addToCartButton: {
    height: 30,
    width: 30,
    backgroundColor: theme.SECONDARY_COLOR,
    borderRadius: theme.CIRCLE_BORDER_RADIUS,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowRadius: 8,
    shadowOpacity: 0.6,
    elevation: 3,
  },
  grid2: {
    justifyContent: 'space-around',
    marginTop: 2,
  },
  pastryPrice2: {
    fontSize: theme.FONT_SIZE_SMALL,
    color: theme.LIGHT_GREY,
  },
  pastryName2: {
    fontSize: theme.FONT_SIZE_NORMAL - 2,
    color: theme.DARK_GREY,
    textAlign: 'center',
    fontWeight: theme.FONT_WEIGHT_BOLD,
  },
  pastryStats2: {
    flexDirection: 'row',
    margin: 'auto',
    alignItems: 'baseline',
  },
  currency2: {
    fontSize: theme.FONT_SIZE_EXTRA_SMALL - 1,
    color: theme.LIGHT_GREY,
  },
  mainContainer: {
    marginHorizontal: 12,
    flexDirection: 'row',
    marginVertical: 7.5,
    borderRadius: theme.BORDER_IMAGE,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.SECONDARY_COLOR,
    shadowRadius: 8,
    shadowOpacity: 0.8,
    elevation: 3,
    backgroundColor: theme.WHITE_COLOR,
  },
  pastryImage: {
    borderRadius: theme.BORDER_IMAGE,
    height: 130,
    width: 130,
  },
  infoContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  pastryDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 2,
    // width: '100%',
  },
  pastryName: {
    fontSize: theme.FONT_SIZE_NORMAL,
    color: theme.DARK_GREY,
    fontWeight: theme.FONT_WEIGHT_BOLD,
  },
  likesContainer: {
    width: 40,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  pastryStats: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    alignSelf: 'center',
    marginTop: 4,
    justifyContent: 'center',
  },
  bestInfoButton: {
    // textAlign: 'right',
    // marginLeft: 'auto',
  },
  bestDiscount: {
    backgroundColor: theme.SUCCESS_COLOR,
    borderRadius: theme.BORDER_IMAGE - 1.5,
    padding: 1.5,
    paddingHorizontal: 3,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowRadius: 8,
    shadowOpacity: 0.8,
    elevation: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bestDiscountText: {
    fontSize: theme.FONT_SIZE_EXTRA_SMALL - 1.5,
    color: theme.WHITE_COLOR,
    marginLeft: 6,
  },
  pastryPrice: {
    fontSize: theme.FONT_SIZE_LARGE,
    color: theme.LIGHT_GREY,
  },
  currency: {
    paddingBottom: 3,
    fontSize: theme.FONT_SIZE_SMALL - 2,
    color: theme.LIGHT_GREY,
  },
  pastryLikes: {
    color: theme.SECONDARY_COLOR,
    fontWeight: '700',
    fontSize: 12,
  },
  pastryIconDetails: {
    flexDirection: 'row',
    marginRight: 12,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  marginRight: {
    marginRight: 7,
  },
});

export default styles;
