import {StyleSheet} from 'react-native';

import theme from '../../../resources/Colors/theme';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: theme.WHITE_COLOR,
    marginTop: 30,
  },
  title: {
    marginTop: 58,
    paddingVertical: 2,
    fontSize: theme.FONT_SIZE_LARGE,
    color: theme.TERTIARY_COLOR,
    paddingHorizontal: 8,
  },
  subTitle: {
    marginVertical: 10,
    paddingVertical: 2,
    fontWeight: theme.FONT_WEIGHT_BOLD,
    color: theme.TERTIARY_COLOR,
    paddingHorizontal: 8,
  },
  editProfileContainer: {
    paddingVertical: 15,
    backgroundColor: theme.WHITE_COLOR,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 3,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1,
  },
  editProfile: {
    textAlign: 'center',
    letterSpacing: 0.8,
    color: theme.TERTIARY_COLOR,
    fontWeight: theme.FONT_WEIGHT_BOLD,
  },
  paymentContainer: {
    paddingHorizontal: 12,
    marginHorizontal: -2,
    marginTop: 16,
    marginBottom: 10,
    borderRadius: theme.BORDER_IMAGE + 10,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 3,
    backgroundColor: theme.WHITE_COLOR,
    zIndex: -999,
  },
  paymentTitle: {
    fontSize: theme.FONT_SIZE_LARGE - 1,
    color: theme.TERTIARY_COLOR,
    fontWeight: theme.FONT_WEIGHT_BOLD,
    paddingVertical: 10,
  },
  budgetContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  budgetTitle: {
    fontSize: theme.FONT_SIZE_SMALL,
    fontWeight: theme.FONT_WEIGHT_BOLD,
    color: theme.DARK_GREY,
  },
  budgetPrice: {
    fontSize: theme.FONT_SIZE_SMALL,
  },
  gradient: {
    marginVertical: 25,
    borderRadius: theme.LARGE_BORDER_RADIUS,
    marginBottom: 20,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowOpacity: 0.8,
    shadowRadius: 6,
    elevation: 3,
    overflow: 'hidden',
  },
  checkoutButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    padding: 13,
  },
  checkoutButtonText: {
    color: theme.WHITE_COLOR,
    fontWeight: theme.FONT_WEIGHT_BOLD,
    marginHorizontal: 60,
  },
  budgetTitleTotal: {
    fontSize: theme.FONT_SIZE_NORMAL,
    fontWeight: theme.FONT_WEIGHT_BOLD,
    color: theme.DARK_GREY,
  },
  budgetPriceTotal: {
    fontSize: theme.FONT_SIZE_NORMAL,
  },
  horizontalLine: {
    borderWidth: 0.9,
    marginVertical: 12,
    borderColor: theme.PRIMARY_COLOR,
  },
  addressContainer: {
    flex: 1,
    position: 'relative',
    marginHorizontal: 8,
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: theme.LARGE_BORDER_RADIUS,
    shadowOffset: {width: 0, height: 2},
    shadowColor: theme.LIGHT_GREY,
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 3,
    backgroundColor: theme.WHITE_COLOR,
  },
  addressButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressButtonText: {
    color: theme.DARK_GREY,
    fontSize: theme.FONT_SIZE_SMALL + 2,
  },
  isAddress: {
    fontSize: theme.FONT_SIZE_LARGE - 2.5,
    color: theme.TERTIARY_COLOR,
    // margin: 8,
  },
  loadingLang: {
    // marginLeft: 12,
    fontSize: theme.FONT_SIZE_SMALL,
    color: theme.LIGHT_GREY,
  },
  loadingContainer: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 5,
  },
  opContainer: {
    marginHorizontal: 5,
    marginVertical: 10,
    alignItems: 'center',
  },
  opCard: {
    height: 65,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.8,
    shadowRadius: 8,
    shadowColor: theme.PRIMARY_COLOR,
    elevation: 3,
    borderRadius: theme.BORDER_IMAGE,
    backgroundColor: theme.WHITE_COLOR,
  },
  opText: {
    paddingVertical: 9,
    color: theme.TERTIARY_COLOR,
    fontSize: theme.FONT_SIZE_SMALL + 1,
    marginLeft: 6,
  },
});

export default styles;
